=== BPELtools/BPEL4Chor-model/doc/BPEL4Chor schema/topology.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	///////////////////////////////////////////////////////////////////////////////////////////// 
	// Initial authors: Gero Decker and Oliver Kopp
	// Created: 6 Dec 2006
	// Purpose: Schema definition for .chor-files
	///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<xs:schema
	xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
	elementFormDefault="qualified" blockDefault="#all">
	<xs:annotation>
		<xs:documentation>
			Schema for service topology definition
		</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd" />

	<xs:simpleType name="QNames">
		<xs:annotation>
			<xs:documentation>
				Taken from WS-BPEL 2.0-spec, since this definition is
				not contained in XML Schema
			</xs:documentation>
		</xs:annotation>
		<xs:restriction>
			<xs:simpleType>
				<xs:list itemType="xs:QName" />
			</xs:simpleType>
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="NCNames">
		<xs:annotation>
			<xs:documentation>
				Newly created, since this definition is
				not contained in XML Schema
			</xs:documentation>
		</xs:annotation>
		<xs:restriction>
			<xs:simpleType>
				<xs:list itemType="xs:NCName" />
			</xs:simpleType>
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="topology" type="tTopology" />
	<xs:complexType name="tTopology">
		<xs:sequence>
			<xs:element ref="participantTypes" minOccurs="1"
				maxOccurs="1" />
			<xs:element ref="participants" minOccurs="1" maxOccurs="1" />
			<xs:element ref="messageLinks" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:NCName" use="required" />
		<xs:attribute name="targetNamespace" type="xs:anyURI" use="required" />
	</xs:complexType>

	<xs:element name="participantTypes" type="tParticipantTypes" />
	<xs:complexType name="tParticipantTypes">
		<xs:sequence>
			<xs:element ref="participantType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="participantType" type="tParticipantType" />
	<xs:complexType name="tParticipantType">
		<xs:attribute name="name" type="xs:NCName" use="required" />
		<xs:attribute name="participantBehaviorDescription" type="xs:QName" use="required" /> 
		<xs:attribute name="processLanguage" type="xs:anyURI" use="optional" default="urn:HPI_IAAS:choreography:profile:2006/12" /> 
	</xs:complexType>

	<xs:element name="participants" type="tParticipants" />
	<xs:complexType name="tParticipants">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element ref="participant" maxOccurs="unbounded" />
				<xs:element ref="participantSet" maxOccurs="unbounded"
					minOccurs="0" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="participant" type="tParticipant" />
	<xs:complexType name="tParticipant">
		<xs:attribute name="name" type="xs:NCName" use="required" />
		<xs:attribute name="type" type="xs:NCName" use="optional" /> <!-- required if not nested in participantTypes -->
		<xs:attribute name="selects" type="NCNames" />
		<xs:attribute name="forEach" type="xs:QName" />
		<xs:attribute name="scope" type="xs:QName" />
		<xs:attribute name="containment" use="optional" default="add-if-not-exists">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="required" />
					<xs:enumeration value="must-add" />
					<xs:enumeration value="add-if-not-exists" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:element name="participantSet" type="tParticipantSet" />
	<xs:complexType name="tParticipantSet">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="participant" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element ref="participantSet" maxOccurs="unbounded" minOccurs="0"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" type="xs:NCName" use="required" />
		<xs:attribute name="type" type="xs:NCName" />
		<xs:attribute name="forEach" type="QNames" />
		<xs:attribute name="scope" type="xs:QName" />
	</xs:complexType>

	<xs:element name="messageLinks" type="tMessageLinks"></xs:element>
	<xs:complexType name="tMessageLinks">
		<xs:sequence>
    	<xs:element ref="messageLink" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="messageLink" type="tMessageLink"></xs:element>
	<xs:complexType name="tMessageLink">
		<xs:attribute name="name" type="xs:NCName" />

		<xs:attribute name="sender" type="xs:NCName" />
		<xs:attribute name="senders" type="NCNames" />
		<xs:attribute name="sendActivity" type="NCNames" />

		<xs:attribute name="bindSenderTo" type="xs:NCName" />

		<xs:attribute name="receiver" type="xs:NCName" use="required" />
		<xs:attribute name="receiveActivity" type="xs:NCName" />

		<xs:attribute name="messageName" type="xs:NCName" use="required" />
		<xs:attribute name="messageType" type="xs:QName" use="required" />
		
		<xs:attribute name="participantRefs" type="NCNames" />		
		<xs:attribute name="copyParticipantRefsTo" type="NCNames" />
	</xs:complexType>

</xs:schema>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/05_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker, Oliver Kopp
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-04-30 17:35:22 +0200 (Mo, 30 Apr 2007) $
  // Purpose: Topology for the one-to-many send pattern
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="P05_topology" 
    targetNamespace="http://example.com/service-interaction-patterns/05"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/05"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="Sender" participantBehaviorDescription="chordef:A" />
    <participantType name="Receiver" participantBehaviorDescription="chordef:B" />
  </participantTypes>

  <participants>
    <participant name="s" type="Sender" />
    <participantSet name="receivers" type="Receiver" forEach="chordef:fe1">
      <participant name="r" type="Receiver" forEach="chordef:fe1"/>
    </participantSet>
  </participants>

  <messageLinks>
    <messageLink sender="s" sendActivity="sendDocument" receiver="r" receiveActivity="receiveDocument" messageName="document" />
  </messageLinks>

</topology>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/04_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker, Oliver Kopp
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-04-30 17:35:22 +0200 (Mo, 30 Apr 2007) $
  // Purpose: Topology for the racing incoming messages pattern
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="P04_topology" 
    targetNamespace="http://example.com/service-interaction-patterns/04"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/04"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="Receiver" participantBehaviorDescription="chordef:A" />
    <participantType name="Sender" participantBehaviorDescription="chordef:B" />
  </participantTypes>

  <participants>
    <participant name="a" type="Receiver" />
    <participantSet name="senders" type="Sender" />
    <participant name="b" type="Sender" />
  </participants>

  <messageLinks>
    <messageLink senders="senders" sendActivities="sendDocumentX" bindSenderTo="b" receiver="a" receiveActivity="receiveDocumentX" messageName="documentX" />
    <messageLink senders="senders" sendActivities="sendDocumentY" bindSenderTo="b" receiver="a" receiveActivity="receiveDocumentY" messageName="documentY" />
  </messageLinks>

</topology>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/09_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker, Oliver Kopp
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-04-30 17:35:22 +0200 (Mo, 30 Apr 2007) $
  // Purpose: Topology for the contingent requests pattern
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="P09_servicetopology" 
    targetNamespace="http://example.com/service-interaction-patterns/09"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/09"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="Requestor" participantBehaviorDescription="chordef:A" />
    <participantType name="Responder" participantBehaviorDescription="chordef:B" />
  </participantTypes>

  <participants>
    <participant name="a" type="Requestor" />
    <participantSet name="responders" type="Responder" forEach="chordef:fe1" >
      <participant name="currentR" type="Responder" forEach="chordef:fe1" />
    </participantSet>
    <participant name="r" type="Responder" containment="required" />
  </participants>

  <messageLinks>
    <messageLink sender="a" sendActivity="sendRequest" receiver="currentR" receiveActivity="receiveRequest" messageName="request" />
    <messageLink sender="r" sendActivity="sendResponse" receiver="a" receiveActivity="receiveResponse" messageName="response" />
  </messageLinks>

</topology>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/06_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker, Oliver Kopp
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-04-30 17:35:22 +0200 (Mo, 30 Apr 2007) $
  // Purpose: Topology for the one-from-many receive pattern
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="P06_topology" 
    targetNamespace="http://example.com/service-interaction-patterns/06"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/06"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="Receiver" participantBehaviorDescription="chordef:A" />
    <participantType name="Sender" participantBehaviorDescription="chordef:B" />
  </participantTypes>

  <participants>
    <participant name="r" type="Receiver" />
    <participantSet name="senders" type="Sender" />
    <participantSet name="mySenders" type="Sender">
      <participant name="s" scope="chordef:rcvScope" />
    </participantSet>
  </participants>

  <messageLinks>
    <messageLink senders="senders" sendActivity="sendDocument" bindSenderTo="s" receiver="r" receiveActivity="receiveDocument" messageName="document" />
  </messageLinks>

</topology>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/x1_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker, Oliver Kopp
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-04-30 17:35:22 +0200 (Mo, 30 Apr 2007) $
  // Purpose: Topology for ...
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="Px1_topology" 
    targetNamespace="http://example.com/service-interaction-patterns/x1"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/x1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="AuctioningService" participantBehaviorDescription="chordef:x1_A" processLanguage="urn:HPI_IAAS:choreography:profile:2006/12" />
    <participantType name="Bidder" participantBehaviorDescription="chordef:x1_B" processLanguage="urn:HPI_IAAS:choreography:profile:2006/12" />
  </participantTypes>

  <participants>
    <participant name="a" type="AuctioningService" />
    <participantSet name="bidders" type="Bidder">
      <participantSet name="acceptedBidders" type="Bidder" forEach="fe1">
        <participant name="b" type="Bidder" forEach="fe1" />
      </participantSet>
    </participantSet>
  </participants>

  <messageLinks>
    <messageLink senders="bidders" sendActivities="sendBid" bindSenderTo="acceptedBidders" receiver="a" receiveActivity="receiveBid" messageName="bid" />
    <messageLink sender="a" sendActivity="sendAnswer" receiver="b" receiveActivity="receiveAnswer" messageName="answer" />
  </messageLinks>

</topology>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/08_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker, Oliver Kopp
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-05-03 15:25:20 +0200 (Do, 03 Mai 2007) $
  // Purpose: Topology for the multi responses pattern
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="P08_topology" 
    targetNamespace="http://example.com/service-interaction-patterns/08"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/08"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="A" participantBehaviorDescription="chordef:A" />
    <participantType name="B" participantBehaviorDescription="chordef:B" />
  </participantTypes>

  <participants>
    <participant name="a" type="A" />
    <participant name="b" type="B" />
  </participants>

  <messageLinks>
    <messageLink sender="a" sendActivity="sendRequest" receiver="b" receiveActivity="receiveRequest" messageName="request" />
    <messageLink sender="b" sendActivity="sendResponse" receiver="a" receiveActivity="receiveResponse" messageName="response" />
  </messageLinks>

</topology>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/03_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker, Oliver Kopp
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-04-30 17:35:22 +0200 (Mo, 30 Apr 2007) $
  // Purpose: Topology for the send/receive pattern
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="P03_topology" 
    targetNamespace="http://example.com/service-interaction-patterns/01"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="Requestor" participantBehaviorDescription="chordef:A" processLanguage="urn:HPI_IAAS:choreography:profile:2006/12" />
    <participantType name="Responder" participantBehaviorDescription="chordef:B" processLanguage="urn:HPI_IAAS:choreography:profile:2006/12" />
  </participantTypes>

  <participants>
    <participant name="a" type="Requestor" />
    <participant name="b" type="Responder" />
  </participants>

  <messageLinks>
    <messageLink sender="a" sendActivity="sendRequest" receiver="b" receiveActivity="receiveRequest" messageName="request" />
    <messageLink sender="b" sendActivity="sendResponse" receiver="a" receiveActivity="receiveResponse" messageName="response" />
  </messageLinks>

</topology>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/11_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker, Oliver Kopp
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-04-30 17:35:22 +0200 (Mo, 30 Apr 2007) $
  // Purpose: Topology for the request with referral pattern
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="P11_topology" 
    targetNamespace="http://example.com/service-interaction-patterns/11"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/11"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="A" participantBehaviorDescription="chordef:A" />
    <participantType name="B" participantBehaviorDescription="chordef:B" />
    <participantType name="C" participantBehaviorDescription="chordef:C" />
  </participantTypes>

  <participants>
    <participant name="a" type="A" selects="b p" />
    <participant name="b" type="B" />
    <participantSet name="p" type="P" forEach="fe1">
      <participant name="pi" forEach="fe1" />
    </participantSet>
  </participants>

  <messageLinks>
    <messageLink sender="a" sendActivity="sendMsg1" receiver="b" receiveActivity="receiveMsg1" messageName="msg1" participantRefs="p" />
    <messageLink sender="b" sendActivity="sendMsg2" receiver="pi" receiveActivity="receiveMsg2" messageName="msg2" />
  </messageLinks>

</topology>
