=== BPELtools/BPEL4Chor-model/doc/BPEL4Chor schema/topology.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	///////////////////////////////////////////////////////////////////////////////////////////// 
	// Initial authors: Gero Decker and Oliver Kopp
	// Created: 6 Dec 2006
	// Purpose: Schema definition for .chor-files
	///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<xs:schema
	xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
	elementFormDefault="qualified" blockDefault="#all">
	<xs:annotation>
		<xs:documentation>
			Schema for service topology definition
		</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd" />

	<xs:simpleType name="QNames">
		<xs:annotation>
			<xs:documentation>
				Taken from WS-BPEL 2.0-spec, since this definition is
				not contained in XML Schema
			</xs:documentation>
		</xs:annotation>
		<xs:restriction>
			<xs:simpleType>
				<xs:list itemType="xs:QName" />
			</xs:simpleType>
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="NCNames">
		<xs:annotation>
			<xs:documentation>
				Newly created, since this definition is
				not contained in XML Schema
			</xs:documentation>
		</xs:annotation>
		<xs:restriction>
			<xs:simpleType>
				<xs:list itemType="xs:NCName" />
			</xs:simpleType>
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="topology" type="tTopology" />
	<xs:complexType name="tTopology">
		<xs:sequence>
			<xs:element ref="participantTypes" minOccurs="1"
				maxOccurs="1" />
			<xs:element ref="participants" minOccurs="1" maxOccurs="1" />
			<xs:element ref="messageLinks" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:NCName" use="required" />
		<xs:attribute name="targetNamespace" type="xs:anyURI" use="required" />
	</xs:complexType>

	<xs:element name="participantTypes" type="tParticipantTypes" />
	<xs:complexType name="tParticipantTypes">
		<xs:sequence>
			<xs:element ref="participantType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="participantType" type="tParticipantType" />
	<xs:complexType name="tParticipantType">
		<xs:attribute name="name" type="xs:NCName" use="required" />
		<xs:attribute name="participantBehaviorDescription" type="xs:QName" use="required" /> 
		<xs:attribute name="processLanguage" type="xs:anyURI" use="optional" default="urn:HPI_IAAS:choreography:profile:2006/12" /> 
	</xs:complexType>

	<xs:element name="participants" type="tParticipants" />
	<xs:complexType name="tParticipants">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element ref="participant" maxOccurs="unbounded" />
				<xs:element ref="participantSet" maxOccurs="unbounded"
					minOccurs="0" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="participant" type="tParticipant" />
	<xs:complexType name="tParticipant">
		<xs:attribute name="name" type="xs:NCName" use="required" />
		<xs:attribute name="type" type="xs:NCName" use="optional" /> <!-- required if not nested in participantTypes -->
		<xs:attribute name="selects" type="NCNames" />
		<xs:attribute name="forEach" type="xs:QName" />
		<xs:attribute name="scope" type="xs:QName" />
		<xs:attribute name="containment" use="optional" default="add-if-not-exists">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="required" />
					<xs:enumeration value="must-add" />
					<xs:enumeration value="add-if-not-exists" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:element name="participantSet" type="tParticipantSet" />
	<xs:complexType name="tParticipantSet">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="participant" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element ref="participantSet" maxOccurs="unbounded" minOccurs="0"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" type="xs:NCName" use="required" />
		<xs:attribute name="type" type="xs:NCName" />
		<xs:attribute name="forEach" type="QNames" />
		<xs:attribute name="scope" type="xs:QName" />
	</xs:complexType>

	<xs:element name="messageLinks" type="tMessageLinks"></xs:element>
	<xs:complexType name="tMessageLinks">
		<xs:sequence>
    	<xs:element ref="messageLink" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="messageLink" type="tMessageLink"></xs:element>
	<xs:complexType name="tMessageLink">
		<xs:attribute name="name" type="xs:NCName" />

		<xs:attribute name="sender" type="xs:NCName" />
		<xs:attribute name="senders" type="NCNames" />
		<xs:attribute name="sendActivity" type="NCNames" />

		<xs:attribute name="bindSenderTo" type="xs:NCName" />

		<xs:attribute name="receiver" type="xs:NCName" use="required" />
		<xs:attribute name="receiveActivity" type="xs:NCName" />

		<xs:attribute name="messageName" type="xs:NCName" use="required" />
		<xs:attribute name="messageType" type="xs:QName" use="required" />
		
		<xs:attribute name="participantRefs" type="NCNames" />		
		<xs:attribute name="copyParticipantRefsTo" type="NCNames" />
	</xs:complexType>

</xs:schema>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/12_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker, Oliver Kopp
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-04-30 17:35:22 +0200 (Mo, 30 Apr 2007) $
  // Purpose: Topology for the relayed request pattern
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="P12_servicetopology" 
    targetNamespace="http://example.com/service-interaction-patterns/12"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/12"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="Client" participantBehaviorDescription="chordef:C" processLanguage="urn:HPI_IAAS:choreography:profile:2006/12" />
    <participantType name="Government" participantBehaviorDescription="chordef:G" processLanguage="urn:HPI_IAAS:choreography:profile:2006/12" />
    <participantType name="ServiceProvider" participantBehaviorDescription="chordef:SP" processLanguage="urn:HPI_IAAS:choreography:profile:2006/12" />
  </participantTypes>

  <participants>
    <participant name="client" type="Client" />
    <participant name="gov" type="Government" selects="prov" />
    <participant name="prov" type="ServiceProvider" />
  </participants>

  <messageLinks>
    <messageLink sender="client" sendActivity="sendRequest" receiver="gov" receiveActivity="receiveRequest" messageName="request" />
    <messageLink sender="gov" sendActivity="delegateRequest" receiver="prov" receiveActivity="receiveRequest" messageName="request" participantRefs="client" />
    <messageLink sender="prov" sendActivity="sendReport" receiver="gov" receiveActivity="receiveReport" messageName="report" />
    <messageLink sender="prov" sendActivity="sendResponse" receiver="client" receiveActivity="receiveResponse" messageName="response" />
  </messageLinks>

</topology>

=== BPELtools/BPEL4Chor-model/examples/interaction patterns/01_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ///////////////////////////////////////////////////////////////////////////////////////////// 
  // Authors:  Gero Decker
  // Created: 6 Dec 2006
  // Last modified: $Date: 2007-04-30 17:35:22 +0200 (Mo, 30 Apr 2007) $
  // Purpose: Topology for the send pattern
  ///////////////////////////////////////////////////////////////////////////////////////////// 
-->
<topology name="P01_topology" 
    targetNamespace="http://example.com/service-interaction-patterns/01"
    xmlns="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12"
    xmlns:chordef="http://example.com/service-interaction-patterns/01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:HPI_IAAS:choreography:schemas:choreography:topology:2006/12 http://www.iaas.uni-stuttgart.de/schemas/bpel4chor/topology.xsd">

  <participantTypes>
    <participantType name="Sender" participantBehaviorDescription="chordef:A" processLanguage="urn:HPI_IAAS:choreography:profile:2006/12" />
    <participantType name="Receiver" participantBehaviorDescription="chordef:B" processLanguage="urn:HPI_IAAS:choreography:profile:2006/12" />
  </participantTypes>

  <participants>
    <participant name="s" type="Sender" />
    <participant name="r" type="Receiver" />
  </participants>

  <messageLinks>
    <messageLink sender="s" sendActivity="sendDocument" receiver="r" receiveActivity="receiveDocument" messageName="document" />
  </messageLinks>

</topology>
